config/routes.rb
DchqCore::Application.routes.draw do

  apipie

  root to: 'pages#index'

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :admin, only: [] do
    collection do
      get :become
    end
  end

  devise_for :users, controllers: { sessions: "sessions", registrations: "registrations", passwords: "passwords" }
  devise_scope :users do
    match 'sign_out' => 'sessions#destroy', via: :get
  end

  resources :stores, only: :update do
    get :set_current, on: :member
    collection do
      get :close
      post :cash_put_out
      get :reopen
    end
  end

  ################################# CUSTOMERS ################################
  resources :customers do
    resources :incidents, only: [:create, :update, :destroy]
    resources :notes, only: [:create]

    collection do
      get :sync_with_mailchimp
      post :export
      post :export_to_qif
      get :mobile_menu
      post :search
      post :update_certification_level_membership
      post :check_certificate
    end

    member do
      get :get_credit_note
      post :add_to_event
      get :check_certification_levels
      get :get_discount_level
      get :recalculate_event_price
      post :get_events
      post :load_sales
      post :load_ecp
    end

    get :update_certification_level_select, on: :collection
  end

  # FIXME: use polymorphic route
  resources :notes, only: [:update, :destroy]

  resources :categories
  resources :brands

  ################################# PRODUCTS ################################
  resources :products do
    collection do
      post :create_extra_option
      post :export
      post :barcode_export
    end
    member do
      post :print_barcode
      get :archived
      get :unarchived
    end
  end

  ################################# SALES ################################
  resources :sales do
    get :history, on: :collection
    get :event_tariffs, on: :collection
    post :pay_for_event, on: :collection
    post :update_extra_options, on: :collection

    collection do
      post :send_receipt_via_email
      get :close
      post :export_to_csv
    end

    member do
      post :add_events
      post :reopen_layby
      post :refund
      get :mark_as_complete
      post :add_product
      post :add_customer
      get  :products_list
      get  :customers_list
      delete :empty
      get :show_email_receipt_form
      get :add_customer_form
      get :add_product_form
      get :search_product
      post :add_note
      post :add_misc_product
    end
  end
  resources :purchase_orders do
    member do
      get :suppliers_list
      post :assign_supplier
      post :remove_supplier
      post :add_product
      get :products_list
      post :empty
      post :add_note
      get :download
      post :set_status
      get :update_order_form_after_send
      post :send_email_to_supplier
      put :set_expected_delivery
      put :update_amend
    end
  end
  resources :payments, only: [:update, :destroy]
  resources :sale_customers, only: [:destroy] do
    put :ignore_events, on: :member
  end

  resources :business_contacts, only: [] do
    resources :notes, only: [:create]
  end

  resources :suppliers do
    resources :notes, only: [:create]
    resources :business_contacts, except: [:index], :path => "/contacts"
    collection do
      get :sync_with_mailchimp
      post :export
    end
  end

  resources :settings, only: [:index, :edit, :update] do
    collection do
      [:user_profile, :stores, :sales, :events, :integrations, :billing, :select_agency, :edit_agency, :trips, :additionals, :edit_mailchimp_step_1,
       :edit_mailchimp_step_2, :print, :import_to_csv_step_1, :switch_store, :servicing, :boats, :emails, :email_example, :clear_data_page,
       :rentals, :restore_sale].each do |route|
        get route
      end
      [:update_stores, :update_store, :update_events, :update_integrations, :update_billing, :update_agency, :update_user].each do |route|
        put route
      end
      [:import_to_csv_step_2, :import, :clear_data].each do |route|
        post route
      end
    end
  end

  namespace :settings do
    resource :xero, only: [:update], controller: "xero" do
      collection do
        get :edit_xero
        get :connect_to_xero
        get :callback
        get :disconnect
        put :update_settings
        post :check_xero_tax_rates
        get :sync
      end
    end
    resource :scubatribe, only: [:create, :new] do
      collection do
        post :signup
      end
    end
  end

  resources :billings, only: [] do
    collection do
      post :stripe_callback
    end
  end

  resources :course_events, except: [:show], :path => "/events/courses" do
    collection do
      get :course_price
    end
    member do
      get :print_event_pickup,    to: 'events#print_event_pickup'
      get :print_event_manifest,  to: 'events#print_event_manifest'
    end
  end
  resources :other_events, except: [:show], :path => "/events/standard" do
    collection do
      get :trip_price
    end
    member do
      get :print_event_pickup,    to: 'events#print_event_pickup'
      get :print_event_manifest,  to: 'events#print_event_manifest'
      post :duplicate
    end
  end

  resources :events, only: [:index, :show, :update] do
    collection do
      get :get_events
      get :get_public_events
      get :list
      get :widget
      post :search
      post :print_resource_manifest
      post :print_staff_roster
      post :print_resource_utilisation
    end
    member do
      get :check_free_sets
      get :cancel_confirmation_no_registrations
      post :cancel
      get :cancel_confirmation_with_registrations
      get :cancel_complete
      get :print_event_pickup
      get :print_resource_manifest
      get :event_user_participants
    end
    resources :event_customer_participants do
      member do
        get :approve
        get :reject_form
        post :reject
        get :reject_paid_form
        post :reject_paid
      end
    end
  end
  resources :event_customer_participants, only: [] do
    delete :remove_from_sale, on: :member
    post :calculate_price, on: :collection
  end

  resources :staff_members do
    collection do
      get :sync_with_mailchimp
      post :export
      get :schedule
    end
    member do
      get :mark_as_day_off
      get :mark_as_available
    end
  end

  resources :users do
    resources :notes, only: [:create]
  end

  ############################################ REPORTS ##############################################
  resources :reports, only: [:index] do
    collection do
      get :sales_by_day
      get :sales_by_month
      get :sales_by_year
      get :sales_by_staff
      get :sales_by_brand
      get :sales_by_category
      get :sales_by_popular
      get :event_sales
      get :financial_reports
      get :edit_finance_report
      put :update_finance_report
    end
  end

  ############################################ BOOKING ##############################################
  resources :bookings, only: [] do
    collection do
      get :step_1
      post :step_2
      post :create_customer
      post :calculate_price
      get :cancel
      get :paypal_complete
    end
  end

  ################################# CUSTOMERS ################################
  resources :gift_card_types do
    member do
      get :pause
      get :resume
    end
  end

  resources :gift_cards, only: [:show, :update]

  resources :credit_notes, only: [:index]
  resources :services do
    collection do
      get :get_type_of_service
      get :add_item
    end
    member do
      post :complete
    end
    resources :service_notes, only: [:edit, :update, :destroy]
    resources :time_intervals, only: [:create] do
      collection do
        post :stop
      end
    end
  end

  resources :certification_levels, only: [:update]
  resources :event_trips, only: [:update]

  namespace :stores do
    resources :boats, only: [:update]
  end

  #RENTAL MODULE
  resources :rentals, except: [:new] do
    member do
      post :add_rental_product
      delete :remove_payment
      post :send_receipt_via_email
    end
  end

  ############################################ RENTAL PRODUCTS ##################################
  resources :rental_products do
    collection do
      get :search
      post :export
    end

    member do
      get :archived
      get :unarchived
    end
  end

  ############################################ SMART LISTS ##################################
  resources :smart_lists do
    member do
      post :send_email
      post :export
    end
    collection do
      get :get_values
    end
  end

  ############################################ REVIEWS / ScubaTribe #############################
  resources :reviews, only: [:index]
  resources :requests, only: [:index]

  ############################################ API ##############################################
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
      end
      resources :companies, only: [:create]
      resources :currencies, only: [:index]
      resources :customers, only: [:index, :show, :create, :update, :destroy]
      resources :events, only: [:index, :show, :create, :update, :destroy] do
        resources :event_user_participants, only: [:update, :create, :destroy]
        resources :event_customer_participants, only: [:update, :create, :destroy]
      end
      [:boats, :stores, :pages, :tax_rates].each do |res|
        resources res, only: [:index]
      end
      resources :categories, only: [:index, :show]
      resources :brands, only: [:index, :show]
      resources :event_trips, only: [:index, :show]
      resources :certification_agencies, only: [:index, :show]
      resources :users, only: [:index] do
        get :info, on: :collection
      end
      resources :sales, only: [:index, :show, :new] do

app/helpers/sales_helper.rb
module SalesHelper
  def finalize_button(sale)
    css_class = 'btn btn-success btn-large input-block-level btn-icon glyphicons ok'
    data_status = sale.refund? ? 'complete_refund' : 'complete'
    title = sale.refund? ? 'Issue Refund' : 'Finalise Sale'

    if data_status.eql?("complete_refund")
      link_to "#{content_tag(:i, nil)}#{title}".html_safe, "#refund_payment_method", class: css_class, :'data-toggle' => :modal
    else
      link_to "#{content_tag(:i, nil)}#{title}".html_safe, "javascript:void(0)", class: "#{css_class} finalize-sale", :"data-status" => data_status
    end
  end
end

app/views/overlays/sales/_add_customer_modal.html.haml
#assign-customer-modal.modal.hide.fade
  .modal-header
    %button.close{ :'aria-hidden' => true, :'data-dismiss' => :modal, type: :button } ×
    %h3= t('overlays.sales.add_customer_modal.header')
  .modal-body.center{style: 'z-index:1001011;'}
    %label{:for => 'cname'}= t('overlays.sales.add_customer_modal.customer_name')
    = text_field_tag 'search_customer', nil, class: 'ui-autocomplete-input'
    %p
      = t('overlays.sales.add_customer_modal.or')
      = link_to t('overlays.sales.add_customer_modal.add_new_customer'), new_customer_path
  .modal-footer
    %button.btn.btn-default{ :'aria-hidden' => true, :'data-dismiss' => :modal, type: :button }= t('views.actions.cancel')

app/views/overlays/sales/_add_note_modal.html.haml
#add-note-modal.modal.hide.fade
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
    %h3= t('sales.details.notes.add_note')
  .modal-body
    .row-fluid
      .span12
        %textarea.span12
  .modal-footer
    %button.btn.btn-default{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"}= t('views.actions.cancel')
    %a.btn.btn-primary{href: ""}= t('sales.details.notes.add_note')

app/views/overlays/sales/_add_payment_modal.html.haml
:ruby
  payment_methods = current_store.payment_methods.map{|pm| [pm.name, pm.id]}
  payment_methods = payment_methods.find_all{|u| u.first != 'Credit Note'}

#add-payment-modal.modal.hide.fade
  .modal-header
    %button.close{ :'aria-hidden' => true, :'data-dismiss' => :modal, type: :button } ×
    %h3= t('overlays.sales.add_payment_modal.header')
  = f.fields_for :payments, @sale.payments.build do |build|
    = build.hidden_field :cashier_id, value: current_user.id
    = build.hidden_field :customer_id
    .modal-body.center{:style => 'overflow:visible;'}
      - if ( !@sale.sale_products.blank? || !@sale.event_customer_participants.blank? ) && @customer.has_credit_note?
        .alert.alert-success{ style: "margin-bottom: 15px;" }
          = t('.credit_note', price: formatted_currency(@customer.credit_note))
          = link_to t('.apply_credit_note'), get_credit_note_customer_path(@customer, sale_id: @sale.id), remote: true, confirm: 'Are you sure?', style: "color: #fff; text-decoration: underline;"

      - unless @sale.complete_refund?
        %h4
          #{t('.amount_due')}: #{ formatted_currency(@sale.change_amount.abs) }
      %p{:style => 'margin-top:10px;'}= t('overlays.sales.add_payment_modal.content')
      = build.text_field :amount, value: nil, placeholder: t('.please_enter_amount')
      %br/
      = build.select :payment_method_id, payment_methods, {}, { class: 'selectpicker' }
      = build.hidden_field :amount_for_search
    .modal-footer
      %button.btn.btn-default{ :'aria-hidden' => true, :'data-dismiss' => :modal, type: :button }= t('views.actions.cancel')
      %button.btn.btn-primary{ type: :submit }= t('overlays.sales.add_payment_modal.add_payment')

app/views/overlays/sales/_cash_put_out_modal.html.haml
:ruby
  out_put_radio = [[t('overlays.sales.cash_put_out_modal.take_out'), true], [t('overlays.sales.cash_put_out_modal.put'), false]]

#cash-put-out-modal.modal.hide.fade
  .modal-header
    %button.close{ :'aria-hidden' => true, :'data-dismiss' => :modal, type: :button } ×
    %h3= t('overlays.sales.cash_put_out_modal.header')
  = simple_form_for current_store, url: cash_put_out_stores_path, method: :post do |f|
    .modal-body
      = f.fields_for :tills, current_store.tills.build do |ff|
        %p{style: 'margin-top:10px;'}= t('overlays.sales.cash_put_out_modal.cash_amount')
        = ff.number_field :amount, label: false, placeholder: "0.00"
        .uniformjs
          = ff.input :take_out, as: :radio_buttons, collection: out_put_radio, label: false, checked: out_put_radio.first
        .row-fluid
          .span12
            = ff.input :notes, as: :text, input_html: { class: 'span12', rows: 2 }

    .modal-footer
      %button.btn.btn-default{ :'aria-hidden' => true, :'data-dismiss' => :modal, type: :button }= t('views.actions.cancel')
      %button.btn.btn-primary{ type: 'submit' }= t('overlays.sales.cash_put_out_modal.update_till')

app/views/overlays/sales/_email_popup.html.haml
:ruby
  sale = @sale.decorate

#email-receipt-modal.modal.hide.fade
  .modal-header
    %button.close{:'aria-hidden' => 'true', :'data-dismiss' => 'modal', :type => 'button'} ×
    %h3= t('overlays.sales.email_popup.header')
  = form_tag send_receipt_via_email_sales_path, :method => :post do
    = hidden_field_tag 'id', sale.id
    .modal-body.center
      = label_tag t('overlays.sales.email_popup.content')
      = text_field_tag 'email', sale.mail_to_castomers
    .modal-footer
      %button.btn.btn-default{:'aria-hidden' => 'true', :'data-dismiss' => 'modal', :type => 'button'}= t('views.actions.cancel')
      = submit_tag t('overlays.sales.email_popup.send'), :class => 'btn btn-primary'

app/views/overlays/sales/_export_to_csv.html.haml
#export-csv.modal.hide.fade
  .modal-header
    %button.close{ :'aria-hidden' => true, :'data-dismiss' => :modal, type: :button } ×
    %h3= t('overlays.sales.export_to_csv.header')
  = form_tag export_to_csv_sales_path do
    .modal-body
      %p= t('overlays.sales.export_to_csv.content')
      .row-fluid
        .span6
          = label_tag t('overlays.sales.export_to_csv.date_from')
          .input-append.date
            = text_field_tag :start_date, nil, class: 'datepicker', style: 'z-index:10010;'
            %span.add-on
              %i.icon-calendar
        .span6
          = label_tag t('overlays.sales.export_to_csv.date_to')
          .input-append.date
            = text_field_tag :end_date, nil, class: 'datepicker', style: 'z-index:10011;'
            %span.add-on
              %i.icon-calendar
    .modal-footer
      %button.btn.btn-default{ :'aria-hidden' => true, :'data-dismiss' => :modal, type: :button }= t('views.actions.cancel')
      = submit_tag t('overlays.sales.export_to_csv.export_data'), class: 'btn btn-primary'

app/views/overlays/sales/_export_to_qif_popup.html.haml
#export-qif.modal.hide.fade
  .modal-header
    %button.close{ :'aria-hidden' => true, :'data-dismiss' => :modal, type: :button } ×
    %h3= t('overlays.sales.export_to_qif_popup.header')
  = form_tag export_to_qif_customers_path, { method: :post } do
    .modal-body
      %p= t('overlays.sales.export_to_qif_popup.content')
      .row-fluid
        .span6
          = label_tag t('overlays.sales.export_to_qif_popup.date_from')
          .input-append.date
            = text_field_tag :start_date, nil, class: 'datepicker', id: 'export_to_qif_starts_at', style: 'z-index:10010;'
            %span.add-on
              %i.icon-calendar
        .span6
          = label_tag t('overlays.sales.export_to_qif_popup.date_to')
          .input-append.date
            = text_field_tag :end_date, nil, class: 'datepicker', id: 'export_to_qif_ends_at', style: 'z-index:10011;'
            %span.add-on
              %i.icon-calendar
    .modal-footer
      %button.btn.btn-default{ :'aria-hidden' => true, :'data-dismiss' => :modal, type: :button }= t('views.actions.cancel')
      = submit_tag t('overlays.sales.export_to_qif_popup.export_data'), class: 'btn btn-primary'

app/views/overlays/sales/_misc_product.html.haml
#misc-product-modal.modal.hide.fade
  .modal-header
    %button.close{:'aria-hidden' => 'true', :'data-dismiss' => 'modal', type: 'button'} ×
    %h3= t('overlays.sales.misc_product.header')
  = form_tag add_misc_product_sale_path(@sale), method: :post, remote: true do
    .modal-body{style: 'overflow: visible;'}
      .row-fluid
        .span6
          %label{for: 'price'}= t('overlays.sales.misc_product.product_price')
          .input-prepend
            %span.add-on= current_store.currency.unit.html_safe
            %input.span12{name: 'misc_product[price]', type: "text"}/
        .span3
          %label{for: 'tax_rate_id'}= t('overlays.sales.misc_product.tax_rate')
          = select_tag 'misc_product[tax_rate_id]', options_for_select(current_store.tax_rates.map{ |t| [t.amount, t.id] }),
                        class: 'selectpicker span12'
      .row-fluid
        .span6
          %label{for: 'category_id'}= t('overlays.sales.misc_product.category')
          = select_tag 'misc_product[category_id]', options_for_select(current_store.categories.map{ |c| [c.name, c.id] }),
                        class: 'select2 span12'
      .row-fluid
        .span9
          %label{ for: 'description' }= t('overlays.sales.misc_product.description')
          = text_area_tag 'misc_product[description]', nil, class: 'span12'
    .modal-footer
      %button.btn.btn-default{ :'aria-hidden' => true, :'data-dismiss' => :modal, type: :button }= t('views.actions.cancel')
      %button.btn.btn-primary{ type: 'submit' }= t('overlays.sales.misc_product.add_misc_product')

app/views/overlays/sales/_product_lookup.html.haml
#product-lookup-modal.modal.hide.fade
  .modal-header
    %button.close{:'aria-hidden' => 'true', :'data-dismiss' => 'modal', type: 'button'} ×
    %h3= t('overlays.sales.product_lookup.header')
  .modal-body.center{style: 'max-height: 500px; overflow-y: auto;'}
    #brands
      %h4= t('overlays.sales.product_lookup.brands')
      %p{style: 'margin-top:15px;'}
      %hr{style: 'margin-top: 20px;'}/
    #categories
      %h4= t('overlays.sales.product_lookup.categories')
      %p{style: 'margin-top:15px;'}
    #products.hide
      %h4= t('overlays.sales.product_lookup.products')
      %p{style: 'margin-top:15px;'}
  .modal-footer
    %button.btn.btn-default{:'aria-hidden' => 'true', :'data-dismiss' => 'modal', type: 'button'}= t('views.actions.cancel')

app/views/overlays/sales/_refund_payment_method.html.haml
:ruby
  payment_methods = current_store.payment_methods.map{|pm| [pm.name, pm.id]}
  payment_methods = payment_methods.find_all{|u| u.first != 'Credit Note'} if @sale.refunded? or @sale.has_only_walkin?

#refund_payment_method.modal.hide.fade
  .modal-header
    %button.close{ :'aria-hidden' => true, :'data-dismiss' => :modal, type: :button } ×
    %h3= t('overlays.sales.refund_payment_method.header')
  .modal-body.center{:style => 'overflow:visible;'}
    %div{class: @sale.has_only_walkin? ? 'hide' : nil}
      %label.radio.uniformjs
        = radio_button_tag 'payment_type', 'refund', true, class: 'refund_type_button'
        = t('overlays.sales.refund_payment_method.refund')
      %label.radio.uniformjs
        = radio_button_tag 'payment_type', 'credit_note', false, class: 'refund_type_button'
        = t('overlays.sales.refund_payment_method.credit_note')
    .new_payment
      = f.fields_for :payments, @sale.payments.build do |build|
        = build.hidden_field :customer_id, value: @sale.customers.first.id
        = build.hidden_field :cashier_id, value: current_user.id
        = build.label :payment_method_id, @sale.refunded? ? t('overlays.sales.refund_payment_method.refund_method') : nil
        = build.select :payment_method_id, payment_methods, {}, {onchange: @sale.refunded? ? '' : "change_payment_amount_placeholder(this)", class: 'selectpicker'}
        = build.hidden_field :amount, value: @sale.grand_total.abs, class: 'payment_amount'

  .modal-footer
    %button.btn.btn-default{ :'aria-hidden' => true, :'data-dismiss' => :modal, type: :button }= t('views.actions.cancel')
    = link_to_function t('overlays.sales.refund_payment_method.issue_refund'), "$(this).closest('form').removeAttr('data-remote').submit()", class: 'btn btn-primary'

app/views/overlays/sales/_refund_total_sale.html.haml
#refund-total-sale.modal.hide.fade
  .modal-header
    %button.close{:'aria-hidden' => 'true', :'data-dismiss' => 'modal', :type => 'button'} ×
    %h3= t('overlays.sales.refund_total_sale.header')
  .modal-body
    %p= t('overlays.sales.refund_total_sale.content')
  .modal-footer
    %button.btn.btn-default{:'aria-hidden' => 'true', :'data-dismiss' => 'modal', :type => 'button'}= t('views.actions.cancel')
    = link_to t('overlays.sales.refund_total_sale.refund_total'), 'javascript:void(0)', class: 'btn btn-primary' 

app/views/overlays/sales/_switch_sale.html.haml
#switch-sale-modal.modal.hide.fade
  .modal-header
    %button.close{:'aria-hidden' => 'true', :'data-dismiss' => 'modal', type: 'button'} ×
    %h3 Switch Sale
  .modal-body.center{style: 'max-height: 500px; overflow-y: auto;'}
    %h4 Active Sales
    - default_sale_list.each do |sale|
      = link_to "##{sale.receipt_id} - #{sale.customers.map(&:full_name).join(', ')}", edit_sale_path(sale), class: "btn btn-small btn-default #{sale.eql?(@sale) ? 'active' : ''}"
  .modal-footer
    %button.btn.btn-default{:'aria-hidden' => 'true', :'data-dismiss' => 'modal', type: 'button'}= t('views.actions.cancel')