config/routes.rb
    member do
      get :get_credit_note
      post :add_to_event
      get :check_certification_levels
      get :get_discount_level
      get :recalculate_event_price
      post :get_events
      post :load_sales
      post :load_ecp
    end

    get :update_certification_level_select, on: :collection
  end

  # FIXME: use polymorphic route
  resources :notes, only: [:update, :destroy]

  resources :categories
  resources :brands

  ################################# PRODUCTS ################################
  resources :products do
    collection do
      post :create_extra_option
      post :export
      post :barcode_export
    end
    member do
      post :print_barcode
      get :archived
      get :unarchived
    end
  end

  ################################# SALES ################################
  resources :sales do
    get :history, on: :collection
    get :event_tariffs, on: :collection
    post :pay_for_event, on: :collection
    post :update_extra_options, on: :collection

    collection do
      post :send_receipt_via_email
      get :close
      post :export_to_csv
    end

    member do
      post :add_events
      post :reopen_layby
      post :refund
      get :mark_as_complete
      post :add_product
      post :add_customer
      get  :products_list
      get  :customers_list
      delete :empty
      get :show_email_receipt_form
      get :add_customer_form
      get :add_product_form
      get :search_product
      post :add_note
      post :add_misc_product
    end
  end
  resources :purchase_orders do
    member do
      get :suppliers_list
      post :assign_supplier
      post :remove_supplier
      post :add_product
      get :products_list
      post :empty
      post :add_note
      get :download
      post :set_status
      get :update_order_form_after_send
      post :send_email_to_supplier
      put :set_expected_delivery
      put :update_amend
    end
  end
  resources :payments, only: [:update, :destroy]
  resources :sale_customers, only: [:destroy] do
    put :ignore_events, on: :member
  end

  resources :business_contacts, only: [] do
    resources :notes, only: [:create]
  end

  resources :suppliers do
    resources :notes, only: [:create]
    resources :business_contacts, except: [:index], :path => "/contacts"
    collection do
      get :sync_with_mailchimp
      post :export
    end
  end

  resources :settings, only: [:index, :edit, :update] do
    collection do
      [:user_profile, :stores, :sales, :events, :integrations, :billing, :select_agency, :edit_agency, :trips, :additionals, :edit_mailchimp_step_1,
       :edit_mailchimp_step_2, :print, :import_to_csv_step_1, :switch_store, :servicing, :boats, :emails, :email_example, :clear_data_page,
       :rentals, :restore_sale].each do |route|
        get route
      end
      [:update_stores, :update_store, :update_events, :update_integrations, :update_billing, :update_agency, :update_user].each do |route|
        put route
      end
      [:import_to_csv_step_2, :import, :clear_data].each do |route|
        post route
      end
    end
  end

  namespace :settings do
    resource :xero, only: [:update], controller: "xero" do
      collection do
        get :edit_xero
        get :connect_to_xero
        get :callback
        get :disconnect
        put :update_settings
        post :check_xero_tax_rates
        get :sync
      end
    end
    resource :scubatribe, only: [:create, :new] do
      collection do
        post :signup
      end
    end
  end

  resources :billings, only: [] do
    collection do
      post :stripe_callback
    end
  end

  resources :course_events, except: [:show], :path => "/events/courses" do
    collection do
      get :course_price
    end
    member do
      get :print_event_pickup,    to: 'events#print_event_pickup'
      get :print_event_manifest,  to: 'events#print_event_manifest'
    end
  end
  resources :other_events, except: [:show], :path => "/events/standard" do
    collection do
      get :trip_price
    end
    member do
      get :print_event_pickup,    to: 'events#print_event_pickup'
      get :print_event_manifest,  to: 'events#print_event_manifest'
      post :duplicate
    end
  end

  resources :events, only: [:index, :show, :update] do
    collection do
      get :get_events
      get :get_public_events
      get :list
      get :widget
      post :search
      post :print_resource_manifest
      post :print_staff_roster
      post :print_resource_utilisation
    end
    member do
      get :check_free_sets
      get :cancel_confirmation_no_registrations
      post :cancel
      get :cancel_confirmation_with_registrations
      get :cancel_complete
      get :print_event_pickup
      get :print_resource_manifest
      get :event_user_participants
    end
    resources :event_customer_participants do
      member do
        get :approve
        get :reject_form
        post :reject
        get :reject_paid_form
        post :reject_paid
      end
    end
  end
  resources :event_customer_participants, only: [] do
    delete :remove_from_sale, on: :member
    post :calculate_price, on: :collection
  end

  resources :staff_members do
    collection do
      get :sync_with_mailchimp
      post :export
      get :schedule
    end
    member do
      get :mark_as_day_off
      get :mark_as_available
    end
  end

  resources :users do
    resources :notes, only: [:create]
  end

  ############################################ REPORTS ##############################################
  resources :reports, only: [:index] do
    collection do
      get :sales_by_day
      get :sales_by_month
      get :sales_by_year
      get :sales_by_staff
      get :sales_by_brand
      get :sales_by_category
      get :sales_by_popular
      get :event_sales
      get :financial_reports
      get :edit_finance_report
      put :update_finance_report
    end
  end

  ############################################ BOOKING ##############################################
  resources :bookings, only: [] do
    collection do
      get :step_1
      post :step_2
      post :create_customer
      post :calculate_price
      get :cancel
      get :paypal_complete
    end
  end

  ################################# CUSTOMERS ################################
  resources :gift_card_types do
    member do
      get :pause
      get :resume
    end
  end

  resources :gift_cards, only: [:show, :update]

  resources :credit_notes, only: [:index]
  resources :services do
    collection do
      get :get_type_of_service
      get :add_item
    end
    member do
      post :complete
    end
    resources :service_notes, only: [:edit, :update, :destroy]
    resources :time_intervals, only: [:create] do
      collection do
        post :stop
      end
    end
  end

  resources :certification_levels, only: [:update]
  resources :event_trips, only: [:update]

  namespace :stores do
    resources :boats, only: [:update]
  end

  #RENTAL MODULE
  resources :rentals, except: [:new] do
    member do
      post :add_rental_product
      delete :remove_payment
      post :send_receipt_via_email
    end
  end

  ############################################ RENTAL PRODUCTS ##################################
  resources :rental_products do
    collection do
      get :search
      post :export
    end

    member do
      get :archived
      get :unarchived
    end
  end

  ############################################ SMART LISTS ##################################
  resources :smart_lists do
    member do
      post :send_email
      post :export
    end
    collection do
      get :get_values
    end
  end

  ############################################ REVIEWS / ScubaTribe #############################
  resources :reviews, only: [:index]
  resources :requests, only: [:index]

  ############################################ API ##############################################
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
      end
      resources :companies, only: [:create]
      resources :currencies, only: [:index]
      resources :customers, only: [:index, :show, :create, :update, :destroy]
      resources :events, only: [:index, :show, :create, :update, :destroy] do
        resources :event_user_participants, only: [:update, :create, :destroy]
        resources :event_customer_participants, only: [:update, :create, :destroy]
      end
      [:boats, :stores, :pages, :tax_rates].each do |res|
        resources res, only: [:index]
      end
      resources :categories, only: [:index, :show]
      resources :brands, only: [:index, :show]
      resources :event_trips, only: [:index, :show]
      resources :certification_agencies, only: [:index, :show]
      resources :users, only: [:index] do
        get :info, on: :collection
      end
      resources :sales, only: [:index, :show, :new] do
        collection do
          get :products
          post :remove_customer
        end
        member do
          post :add_customer
          post :add_product
          post :send_receipt
          post :add_misc_product
        end
      end
      resources :reports, only: [] do
        collection do
          [:sales_by_brand, :sales_by_category, :sales_by_day, :sales_by_products, :sales_by_staff_member,
           :financial_reports].each do |route|
            get route
          end
          match '/financial_reports/:id' => 'reports#financial_report_details', via: :get
          match '/financial_reports/:id' => 'reports#update_finance_report', via: :put
        end
      end
      resources :products, except: [:new, :edit]
    end
  end

  resources :pages, only: [] do
    collection do
      %w(change_current_store delete_image no_access search complete_setup).each do |route|
        get route.to_sym
      end
      %w[send_message send_support_request].each do |route|
        post route.to_sym
      end

app/models/category.rb
class Category < ActiveRecord::Base
  has_paper_trail

  belongs_to :store
  has_many :products, dependent: :destroy, include: [:brand, :supplier]
  has_many :miscellaneous_products, dependent: :destroy
  has_many :sales, through: :products, uniq: true, include: [:discount]
  has_many :sale_products, through: :sales, uniq: true
  has_many :rental_products, dependent: :destroy

  validates :store, existence: true
  validates :name, presence: true

  attr_accessible :name, :description

  scope :out_of_stock, scoped

  #TODO: memcache needed
  def average_month_sales
    self.sales.for_the_last_month.each do |s|
      s.filter_by_id = self.id
      s.filter_by_model = :category
    end.mean(:calc_grand_total)
  end

  def last_sale_date
    pretendent = self.sales.by_creation.last
    return I18n.t('brands.index.not_available') unless pretendent

    I18n.l(pretendent.created_at, format: :default)
  end

  def all_product_ids
    products.pluck(:id) + miscellaneous_products.pluck(:id)
  end
end

app/controllers/Api/V1/categories_controller.rb
module Api
  module V1
    class CategoriesController < Api::V1::ApplicationController
      actions :index

      api :GET, '/v1/categories', 'Get all categories for store'
      param_group :store_api_key, Api::V1::ApplicationController
      formats [:json]
      example '
      ########### Request Example #################
      # URL
      https://api.divecentrehq.com/api/v1/categories

      # Request Body
      {
        user_token: <USER_TOKEN>,
        store_api_key: <STORE_API_KEY>
      }

      ########### Response Example ################
      {
        "categories": [
          {
            "id": 73,
            "name": "Masks",
            "description": "",
            "created_at": "2012-02-11T07:36:09Z",
            "updated_at": "2012-02-11T07:36:09Z"
          },
          {
            "id": 74,
            "name": "BCDs",
            "description": "",
            "created_at": "2012-02-11T07:36:19Z",
            "updated_at": "2012-02-11T07:36:19Z"
          }
        ]
      }
      '
      def index
        super
      end

      api :GET, '/v1/categories/:id', 'Get category details'
      param_group :store_api_key, Api::V1::ApplicationController
      param :id, Integer, required: true, desc: 'Category ID'
      formats [:json]
      example '
      ########### Request Example #################
      # URL
      https://api.divecentrehq.com/api/v1/categories/1

      # Request Body
      {
        user_token: <USER_TOKEN>,
        store_api_key: <STORE_API_KEY>,
        id: 1
      }

      ########### Response Example ################
     {
       category: {
         id: 876,
         name: "HOG",
         description: null,
         created_at: "2014-03-06T21:09:56Z",
         updated_at: "2014-03-06T21:09:56Z",
         units_in_stock: 4,
         stock_value: "28.00",
         avg_monthly_sale: 0,
         last_sale: "28 Aug, 2014 01:26am",
         products: [
           {
             id: 24780,
             accounting_code: "",
             archived: false,
             barcode: "",
             commission_rate_money: null,
             description: "We took a classic and made it better!",
             low_inventory_reminder: 5,
             markup: 0.0,
             name: "HOG Tech 2 Fin - Black - XXL",
             number_in_stock: 0,
             offer_price: null,
             retail_price: "150.0",
             sent_at: null,
             sku_code: "EDG0160-2X-BK",
             supplier_code: "",
             supply_price: "80.0"
           },
         ]
       }
      }
      '
      def show
        super
      end

      private
      def begin_of_association_chain
        current_store
      end
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  decorates_assigned :category, :categories

  load_and_authorize_resource

  respond_to :html
  respond_to :js, only: :destroy
  respond_to :json, only: [:index, :show]

  def index
    index! do |format|
      format.json{ render json: end_of_association_chain.order('name asc').to_json(only: [:id, :name]) }
    end
  end

  def show
    show! do |format|
      format.html {
        @q = resource.products.ransack(params[:q])
        @q.sorts = 'name asc' if @q.sorts.empty?
        @products = @q.result.page(params[:page]).per(Figaro.env.default_pagination.to_i)
      }
      format.json {
        list_of_products = if params[:type] == 'rental'
                             resource.rental_products.select{ |pr| pr.number_of_available > 0 }
                           else
                             resource.products
                           end.sort{ |a,b| a.name.downcase <=> b.name.downcase }
        render json: list_of_products.to_json(only: [:id, :name])
      }
    end
  end

  protected
  def begin_of_association_chain
    current_store
  end

  def collection
    @q = end_of_association_chain.ransack(params[:q])
    @q.sorts = 'name asc' if @q.sorts.empty?
    @categories = @q.result.page(params[:page]).per(Figaro.env.default_pagination)
  end
end

app/views/categories/_category.html.haml
%tr{ :id => dom_id(category) }
  %td.important
    = link_to category.name, category_path(category)
  %td= category.products_count
  %td= category.products_in_stock
  %td= formatted_currency(category.products_stock_value)
  %td= formatted_currency(category.average_month_sales)
  %td= category.last_sale_date

app/views/categories/_form.html.haml
= simple_form_for resource, validate: true do |f|
  = f.error_messages
  .innerLR
    .widget.widget-tabs
      .widget-head
        %ul
          %li.active
            = link_to '#productDescriptionTab', class: 'glyphicons font', :'data-toggle' => 'tab' do
              %i>
              = t('categories.form.category_details')
      .widget-body
        .tab-content
          #productDescriptionTab.tab-pane.active
            .row-fluid
              .span3
                %strong= t('categories.form.category_name')
                %p.muted= t('categories.form.category_name_text')
              .span6
                = f.input :name, input_html: { class: 'span11' }
            %hr.separator.bottom/
            .row-fluid
              .span3
                %strong= t('categories.form.description')
                %p.muted= t('categories.form.description_text')
              .span9
                = f.input :description, as: :text, input_html: { style: 'width: 96%;', rows: '2' }
    .heading-buttons
      .buttons.pull-right{:style => 'margin: 0;'}
        %button.btn.btn-primary.btn-icon.glyphicons.ok_2{ type: 'submit' }
          %i
          = t('categories.form.save')
      .clearfix

app/views/categories/_table_headers.html.haml
%thead
  %tr.ransack_links
    %th= sort_link @q, :name, t('brands.table_headers.category')
    %th= sort_link @q, :products_count, t('brands.table_headers.skus')
    %th= sort_link @q, :products_in_stock, t('brands.table_headers.units_stock')
    %th= sort_link @q, :products_stock_value, t('brands.table_headers.stock_value')
    %th= sort_link @q, :average_month_sales, t('brands.table_headers.average_monthly_sale')
    %th= sort_link @q, :last_sale_date, t('brands.table_headers.last_sale')

app/views/categories/edit.html.haml
%ul.breadcrumb
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('categories.edit.home')
  %li.divider
  %li= t('categories.edit.sales')
  %li.divider
  %li= t('categories.edit.categories')
.innerLR
  .row-fluid
    .span4
      %h3.heading-mosaic= t('categories.edit.edit_category')
= render 'form'

app/views/categories/index.html.haml
%ul.breadcrumb
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('categories.index.home')
  %li.divider
  %li= t('categories.index.sales')
  %li.divider
  %li= t('categories.index.categories')
.innerLR
  .row-fluid
    .span4
      %h3.heading-mosaic= t('categories.index.categories')
    .span8.right
      - if can?(:create, Category)
        .buttons.hidden-print
          = link_to  new_category_path, class: 'btn btn-primary btn-icon glyphicons circle_plus' do
            %i
            = t('categories.index.new_category')
.innerLR
  .widget
    .widget-head
      %h4.heading.glyphicons.list
        %i
        = t('categories.index.categories')
    .widget-body
      %table.table.table-bordered.table-condensed.table-striped.table-primary.table-vertical-center.checkboxs.js-table-sortable
        = render 'categories/table_headers'
        %tbody
          = render categories
      .separator.top.form-inline.small
        = t('categories.index.total_categories')
        = collection.total_count
        .pagination.pagination-small.pull-right{style: 'margin: 0;'}
          = paginate collection
        .clearfix

app/views/categories/new.html.haml
%ul.breadcrumb
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('categories.new.home')
  %li.divider
  %li= t('categories.new.sales')
  %li.divider
  %li= t('categories.new.categories')
.innerLR
  .row-fluid
    .span4
      %h3.heading-mosaic= t('categories.new.add_category')
= render 'form'

app/views/categories/show.html.haml
%ul.breadcrumb
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('categories.show.home')
  %li.divider
  %li= t('categories.show.sales')
  %li.divider
  %li= link_to t('categories.show.categories'), categories_path
  %li.divider
  %li= t('categories.show.details')
.innerLR
  .row-fluid
    .span4
      %h3.heading-mosaic
        = t('categories.show.categories')
        %span
          |
          = category.name
    .span8.right
      - if can? :update, resource
        .buttons.hidden-print
          = link_to edit_category_path(category), class: 'btn btn-small btn-default btn-icon glyphicons pencil' do
            %i
            = t('categories.show.edit_category')
.innerLR
  .row-fluid
    .span8
      %h4= category.name
      %p= category.description
    .span4
      %h4
        %span= t('categories.show.category_information')
      .separator.bottom
      = render 'products/group_info', association: category
  .row-fluid
    .span12
      .widget
        .widget-head
          %h4.heading.glyphicons.fins
            %i>
            = t('categories.show.skus')
        .widget-body
          %table.table.table-bordered.table-condensed.table-striped.table-primary.table-vertical-center
            = render 'products/table_headers', hide_category: true
            %tbody
              = render @products.decorate, hide_category: true
          .separator.top.form-inline.small
            = t('categories.show.total_products')
            = @products.total_count
            .pagination.pagination-small.pull-right{style: 'margin: 0;'}
              = paginate @products
            .clearfix
%p
  - if category.products.empty?
    = link_to category, method: :delete, confirm: 'Are you sure?', class: 'btn btn-default btn-mini btn-icon glyphicons bin' do
      %i>
      = t('categories.show.delete_category')