config/routes.rb
DchqCore::Application.routes.draw do

  apipie

  root to: 'pages#index'

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :admin, only: [] do
    collection do
      get :become
    end
  end

  devise_for :users, controllers: { sessions: "sessions", registrations: "registrations", passwords: "passwords" }
  devise_scope :users do
    match 'sign_out' => 'sessions#destroy', via: :get
  end

  resources :stores, only: :update do
    get :set_current, on: :member
    collection do
      get :close
      post :cash_put_out
      get :reopen
    end
  end

  ################################# CUSTOMERS ################################
  resources :customers do
    resources :incidents, only: [:create, :update, :destroy]
    resources :notes, only: [:create]

    collection do
      get :sync_with_mailchimp
      post :export
      post :export_to_qif
      get :mobile_menu
      post :search
      post :update_certification_level_membership
      post :check_certificate
    end

    member do
      get :get_credit_note
      post :add_to_event
      get :check_certification_levels
      get :get_discount_level
      get :recalculate_event_price
      post :get_events
      post :load_sales
      post :load_ecp
    end

    get :update_certification_level_select, on: :collection
  end

  # FIXME: use polymorphic route
  resources :notes, only: [:update, :destroy]

  resources :categories
  resources :brands

  ################################# PRODUCTS ################################
  resources :products do
    collection do
      post :create_extra_option
      post :export
      post :barcode_export
    end
    member do
      post :print_barcode
      get :archived
      get :unarchived
    end
  end

  ################################# SALES ################################
  resources :sales do
    get :history, on: :collection
    get :event_tariffs, on: :collection
    post :pay_for_event, on: :collection
    post :update_extra_options, on: :collection

    collection do
      post :send_receipt_via_email
      get :close
      post :export_to_csv
    end

    member do
      post :add_events
      post :reopen_layby
      post :refund
      get :mark_as_complete
      post :add_product
      post :add_customer
      get  :products_list
      get  :customers_list
      delete :empty
      get :show_email_receipt_form
      get :add_customer_form
      get :add_product_form
      get :search_product
      post :add_note
      post :add_misc_product
    end
  end
  resources :purchase_orders do
    member do
      get :suppliers_list
      post :assign_supplier
      post :remove_supplier
      post :add_product
      get :products_list
      post :empty
      post :add_note
      get :download
      post :set_status
      get :update_order_form_after_send
      post :send_email_to_supplier
      put :set_expected_delivery
      put :update_amend
    end
  end
  resources :payments, only: [:update, :destroy]
  resources :sale_customers, only: [:destroy] do
    put :ignore_events, on: :member
  end

  resources :business_contacts, only: [] do
    resources :notes, only: [:create]
  end

  resources :suppliers do
    resources :notes, only: [:create]
    resources :business_contacts, except: [:index], :path => "/contacts"
    collection do
      get :sync_with_mailchimp
      post :export
    end
  end

  resources :settings, only: [:index, :edit, :update] do
    collection do
      [:user_profile, :stores, :sales, :events, :integrations, :billing, :select_agency, :edit_agency, :trips, :additionals, :edit_mailchimp_step_1,
       :edit_mailchimp_step_2, :print, :import_to_csv_step_1, :switch_store, :servicing, :boats, :emails, :email_example, :clear_data_page,
       :rentals, :restore_sale].each do |route|
        get route
      end
      [:update_stores, :update_store, :update_events, :update_integrations, :update_billing, :update_agency, :update_user].each do |route|
        put route
      end
      [:import_to_csv_step_2, :import, :clear_data].each do |route|
        post route
      end
    end
  end

  namespace :settings do
    resource :xero, only: [:update], controller: "xero" do
      collection do
        get :edit_xero
        get :connect_to_xero
        get :callback
        get :disconnect
        put :update_settings
        post :check_xero_tax_rates
        get :sync
      end
    end
    resource :scubatribe, only: [:create, :new] do
      collection do
        post :signup
      end
    end
  end

  resources :billings, only: [] do
    collection do
      post :stripe_callback
    end
  end

  resources :course_events, except: [:show], :path => "/events/courses" do
    collection do
      get :course_price
    end
    member do
      get :print_event_pickup,    to: 'events#print_event_pickup'
      get :print_event_manifest,  to: 'events#print_event_manifest'
    end
  end
  resources :other_events, except: [:show], :path => "/events/standard" do
    collection do
      get :trip_price
    end
    member do
      get :print_event_pickup,    to: 'events#print_event_pickup'
      get :print_event_manifest,  to: 'events#print_event_manifest'
      post :duplicate
    end
  end

  resources :events, only: [:index, :show, :update] do
    collection do
      get :get_events
      get :get_public_events
      get :list
      get :widget
      post :search
      post :print_resource_manifest
      post :print_staff_roster
      post :print_resource_utilisation
    end
    member do
      get :check_free_sets
      get :cancel_confirmation_no_registrations
      post :cancel
      get :cancel_confirmation_with_registrations
      get :cancel_complete
      get :print_event_pickup
      get :print_resource_manifest
      get :event_user_participants
    end
    resources :event_customer_participants do
      member do
        get :approve
        get :reject_form
        post :reject
        get :reject_paid_form
        post :reject_paid
      end
    end
  end
  resources :event_customer_participants, only: [] do
    delete :remove_from_sale, on: :member
    post :calculate_price, on: :collection
  end

  resources :staff_members do
    collection do
      get :sync_with_mailchimp
      post :export
      get :schedule
    end
    member do
      get :mark_as_day_off
      get :mark_as_available
    end
  end

  resources :users do
    resources :notes, only: [:create]
  end

  ############################################ REPORTS ##############################################
  resources :reports, only: [:index] do
    collection do
      get :sales_by_day
      get :sales_by_month
      get :sales_by_year
      get :sales_by_staff
      get :sales_by_brand
      get :sales_by_category
      get :sales_by_popular
      get :event_sales
      get :financial_reports
      get :edit_finance_report
      put :update_finance_report
    end
  end

  ############################################ BOOKING ##############################################
  resources :bookings, only: [] do
    collection do
      get :step_1
      post :step_2
      post :create_customer
      post :calculate_price
      get :cancel
      get :paypal_complete
    end
  end

  ################################# CUSTOMERS ################################
  resources :gift_card_types do
    member do
      get :pause
      get :resume
    end
  end

  resources :gift_cards, only: [:show, :update]

  resources :credit_notes, only: [:index]
  resources :services do
    collection do
      get :get_type_of_service
      get :add_item
    end
    member do
      post :complete
    end
    resources :service_notes, only: [:edit, :update, :destroy]
    resources :time_intervals, only: [:create] do
      collection do
        post :stop
      end
    end
  end

  resources :certification_levels, only: [:update]
  resources :event_trips, only: [:update]

  namespace :stores do
    resources :boats, only: [:update]
  end

  #RENTAL MODULE
  resources :rentals, except: [:new] do
    member do
      post :add_rental_product
      delete :remove_payment
      post :send_receipt_via_email
    end
  end

  ############################################ RENTAL PRODUCTS ##################################
  resources :rental_products do
    collection do
      get :search
      post :export
    end

    member do
      get :archived
      get :unarchived
    end
  end

  ############################################ SMART LISTS ##################################
  resources :smart_lists do
    member do
      post :send_email
      post :export
    end
    collection do
      get :get_values
    end
  end

  ############################################ REVIEWS / ScubaTribe #############################
  resources :reviews, only: [:index]
  resources :requests, only: [:index]

  ############################################ API ##############################################
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
      end
      resources :companies, only: [:create]
      resources :currencies, only: [:index]
      resources :customers, only: [:index, :show, :create, :update, :destroy]
      resources :events, only: [:index, :show, :create, :update, :destroy] do
        resources :event_user_participants, only: [:update, :create, :destroy]
        resources :event_customer_participants, only: [:update, :create, :destroy]
      end
      [:boats, :stores, :pages, :tax_rates].each do |res|
        resources res, only: [:index]
      end
      resources :categories, only: [:index, :show]
      resources :brands, only: [:index, :show]
      resources :event_trips, only: [:index, :show]
      resources :certification_agencies, only: [:index, :show]
      resources :users, only: [:index] do
        get :info, on: :collection
      end
      resources :sales, only: [:index, :show, :new] do

app/helpers/sales_helper.rb
module SalesHelper
  def finalize_button(sale)
    css_class = 'btn btn-success btn-large input-block-level btn-icon glyphicons ok'
    data_status = sale.refund? ? 'complete_refund' : 'complete'
    title = sale.refund? ? 'Issue Refund' : 'Finalise Sale'

    if data_status.eql?("complete_refund")
      link_to "#{content_tag(:i, nil)}#{title}".html_safe, "#refund_payment_method", class: css_class, :'data-toggle' => :modal
    else
      link_to "#{content_tag(:i, nil)}#{title}".html_safe, "javascript:void(0)", class: "#{css_class} finalize-sale", :"data-status" => data_status
    end
  end
end

app/views/sales/_details.html.haml
:ruby
  form ||= nil
  if @sale.refund?
    payments = @sale.parent.try(:payment_tendered)
  else
    payments = @sale.try(:payment_tendered)
  end
  sale = @sale.decorate

%table.table.table-bordered.table-striped.table-vertical-center.table-condensed
  %thead
    %tr
      %th= t('sales.details.t_scu_product')
      %th.center{style: 'width: 80px;'}= t('sales.details.t_unit_price')
      %th.center{style: 'width: 80px;'}= t('sales.details.t_tax')
      %th.center{style: 'width: 80px;'}= t('sales.details.t_quantity')
      %th.center{style: 'width: 80px;'}= t('sales.details.t_discount')
      %th.center{style: 'width: 80px;'}= t('sales.details.t_sub_total')
  %tbody
    = render partial: 'sales/sale_product', collection: sale.sale_products.sort{ |a ,b| a.id <=> b.id }, locals: { is_editable: is_editable, form: form }

.separator.bottom
.row-fluid
  .span6
    %p
      - if @sale.active?
        = link_to empty_sale_path(@sale), method: :delete, remote: true, confirm: t('views.actions.confirm') do
          %i.icon-eraser
          = t('sales.details.empty_cart')
      - if @sale.active? || (@sale.complete? && !current_store.close? && current_user.manager? && @sale.children.blank?) || @sale.refund?
        = link_to sale_path(@sale), method: :delete, remote: @sale.active?, style: 'color: red; margin-left: 25px;', confirm: t('views.actions.confirm') do
          %i.icon-ban-circle
          = t('sales.details.delete_cart')
      - if @sale.active?
        = link_to 'javascript:void(0)', class: 'save_as_layby', :"data-status" => "layby", style: 'margin-left: 25px;' do
          %i.icon-inbox
          = t('sales.details.save_as_lay_by')
      - if @sale.note.blank? && @sale.active?
        %a#add-note{'data-toggle' => 'modal', href: '#add-note-modal', style: 'margin-left: 25px;'}
          %i.icon-bookmark
          = t('sales.details.notes.add_note')

    %p#notes
      - if @sale.note.present?
        = render 'sales/notes'
  .span5.pull-right
    %table.table.table-borderless.table-condensed.cart_total
      %tbody
        %tr
          - if is_editable && !sale.refund? && !@sale.line_items_has_discount
            %td.right= t('sales.details.overall_discount')
            %td.right.strong.discount
              = form.fields_for :discount, @sale.discount.nil? ? @sale.build_discount : @sale.discount
              .clear
          - if sale.completed? && !@sale.calc_discount.zero?
            %td.right= t('sales.details.overall_discount')
            %td.right.strong.discount
              = formatted_currency @sale.calc_discount
              .clear
        %tr
          %td.right
            = t('sales.details.sub_total')
            = current_store.print_tax
          %td.right.strong= sale.sub_total_abs
        - if @sale.customers.first.try(:zero_tax_rate?)
          %tr
            %td.right
              = t('sales.details.tax_exempt')
            %td.right.strong
              \- #{sale.tax_rate_total_abs}
        - else
          %tr
            %td.right= t('sales.details.tax')
            %td.right.strong= sale.tax_rate_total_abs
        - if @sale.refunded? && @sale.parent && @sale.parent.status == 'layby_refund'
          %tr
            %td.right Payments To Date:
            %td.right.strong= formatted_currency(@sale.grand_total.abs)
        - if @sale.completed?
          %tr
            %td{colspan: '2'}
              .separator.bottom
              %span.label.right.label-block.large
                = t('sales.details.net_due')
                = sale.grand_total_abs
          %tr
            %td{colspan: '2'}
              .separator.bottom
              %span.label.right.label-block.large
                = t('sales.details.less_total_payment')
                = formatted_currency(sale.payments.sum(:amount))
        - else
          %tr
            %td{colspan: '2'}
              - unless @sale.can_be_completed?
                .alert.alert-error{style: 'text-align:center; padding: 8px !important;'}
                  - if @sale.complete_refund?
                    %span{style: 'font-size:16px;'} #{t('sales.details.amount_due')}: #{formatted_currency(0)}
                  - else
                    %span{style: 'font-size:16px;'} #{t('sales.details.amount_due')}: #{formatted_currency(@sale.change_amount.abs)}
              - else
                .alert.alert-info{style: 'text-align:center; padding: 8px !important;'}
                  %span{style: 'font-size:16px;'} #{t('sales.details.change')}: #{formatted_currency(@sale.change_amount.abs)}
          %tr
            %td{colspan: '2'}
              - if @sale.can_be_completed? || @sale.refund?
                = finalize_button @sale
                = render 'overlays/sales/refund_payment_method', f: form if @sale.refund?
              - else
                - if !@sale.completed? && !@sale.refunded? && !@sale.complete_refund?
                  = link_to '#add-payment-modal', class: 'btn btn-primary btn-large input-block-level btn-icon glyphicons coins', :'data-toggle' => :modal, style: 'text-align:center; text-transform:uppercase;' do
                    %i>
                    = t('sales.details.add_payment')
                  = render 'overlays/sales/add_payment_modal', f: form
        %tr
          %td{colspan: '2'}
            .widget-timeline.hidden-print{style: 'margin-top:10px'}
              %ul.list-timeline
                - @sale.payments.each do |p|
                  - next if p.new_record?
                  %li
                    %span.date= p.created_at.strftime('%d/%m')
                    %span.glyphicons.activity-icon.coins
                      %i
                    %span.ellipsis
                      %a{href: 'javascript:void(0)'}= formatted_currency(p.amount)
                      = p.payment_method.name.upcase
                    - if !@sale.completed? && !@sale.refunded?
                      %span.pull-right.hidden-print{style: 'float:right;'}
                        = link_to p, method: :delete, remote: true, style: 'color:red;', confirm: 'Are you sure?' do
                          %i.icon-ban-circle
        - if @sale.completed?
          %tr
            %td{colspan: '2'}
              .separator.bottom
              %span.label.right.label-block.large{style: 'background: #609450; color: #fff; text-shadow: none !important;'}
                = @sale.paid? ? t('sales.details.change') : (@sale.refund? ? t('sales.details.amount_to_refund') : t('sales.details.amount_due'))
                = formatted_currency(@sale.change_amount.abs)

        - if @sale.can_be_refunded? && @sale.completed?
          %tr.refund-total.hide
            %td{colspan: '2'}
              = link_to 'javascript:void(0)', class: 'btn btn-info btn-large input-block-level btn-icon glyphicons history hidden-print', id: 'whole_refund', :'data-toggle' => 'modal', style: 'text-align:center; text-transform:uppercase;' do
                %i>
                = t('sales.details.refund_total')

        %tr.hidden-print
          %td{colspan: '2'}
            .row-fluid
              .span6
                - if current_store.printer_type == 'tsp'
                  = link_to 'javascript:void(0)', onclick: "onSendMessage()", class: 'btn btn-default btn-default btn-icon glyphicons print input-block-level', style: 'text-align:center; text-transform:uppercase;' do
                    %i>
                    = t('sales.show.print_receipt')
                - else
                  = link_to '', class: 'btn btn-default btn-default btn-icon glyphicons print print-receipt input-block-level', style: 'text-align:center; text-transform:uppercase;' do
                    %i>
                    - unless @sale.active?
                      = t('sales.show.print_receipt')
                    - else
                      = t('sales.show.print_receipt_invoice')
              .span6
                = link_to '#email-receipt-modal', class: 'btn btn-default btn-icon glyphicons envelope input-block-level', style: 'text-align:center; text-transform:uppercase;', :'data-toggle' => 'modal' do
                  %i>
                  - unless @sale.active?
                    = t('sales.show.email_receipt')
                  - else
                    = t('sales.show.email_receipt_invoice')

- content_for :overlays do
  = render 'overlays/sales/email_popup'

= render 'overlays/sales/add_note_modal'

.hide
  #print
    - if current_store.printer_type.eql?("80mm")
      = render 'receipts/sales/print', print: true
    - elsif current_store.printer_type.eql?("70mm")
      = render 'receipts/sales/print_70'
    - else
      = render 'receipts/sales/tsp'

app/views/sales/_history_sale.html.haml
%tr{ :id => dom_id(sale) }
  %td.important
    = link_to sale.receipt_id, sale_path(sale)
  %td= sale.created_at
  %td= sale.product_quantity
  %td= sale.value
  %td= sale.status_div

app/views/sales/_misc_product_item.html.haml
%tr
  %td.product
    .media
      %span.media-object.pull-left
        %img{height: "30px", src: "https://app.divecentrehq.com/assets/missing/product/thumb.gif", width: "30px"}/
      .media-body
        - if !@sale.refunded? && @sale.completed? && record.can_be_refunded?
          .pull-right.hidden-print
            %label.refund-checkbox.uniformjs{style: "margin-top:6px;"}
              = check_box_tag 'sale_product_id[]', record.id
              Refund Items
            .refund-total-dropdown.hide
              = select_tag 'refund_quantity[]', options_for_select((1..record.quantity).entries) , class: 'span1 select2'
        %span.heading
          %h5
            = record.productable_description
          %span= record.productable_category_name
  %td.center= record.unit_price
  %td.center= record.tax_rate
  %td.center.quantity
    - if is_editable && !@sale.refund?
      = form.fields_for :sale_products, record do |sp_form|
        = sp_form.select :quantity, (0..SaleProduct::QUANTITY_LIMIT).to_a, { selected: record.quantity }, { class: 'span1 selectpicker' }
    - else
      = record.quantity
  %td.center.discount
    - if is_editable && !@sale.refund? && !@sale.has_discount
      = form.fields_for :sale_products, record do |sp_form|
        = sp_form.fields_for :prod_discount, record.prod_discount ? record.prod_discount : record.build_prod_discount
    - else
      = til formatted_discount(record.prod_discount)
  %td.center= record.price

app/views/sales/_notes.html.haml
%strong= t('sales.details.notes.notes')
\-
%a#edit-note{'data-toggle' => 'modal', href: '#add-note-modal'}= t('helpers.application.edit')
%br/
%span#note-holder
  = @sale.note.html_safe

app/views/sales/_sale.html.haml
%tr
  %td.important
    = link_to sale.receipt_id, sale.sale_path
  %td= sale.created_at
  %td= sale.creator_name
  %td= sale.customers
  %td= sale.grand_total_abs
  %td= formatted_currency(sale.to_pay)
  %td= sale.human_status

app/views/sales/_sale_customer.html.haml
%table.table.table-invoice
  %tbody
    %tr
      %td{:style => 'width: 50%; border-right: 1px solid #e5e5e5;'}
        %h4
          = customer.full_name
          %span= t('sales.sale_customer.mark_customer')
        %address.margin-none
          = customer.full_address
          %br/
          = t('sales.sale_customer.tel')
          = til customer.telephone
          %br/
          = t('sales.sale_customer.email')
          = til customer.email
          - unless customer.tax_id.blank?
            %br/
            = t('sales.sale_customer.tax_id')
            = til customer.tax_id
      %td.right
        %h4
          = sale.store_name
          %span= t('sales.sale_customer.mark_merchant')
        %address.margin-none
          = sale.company_address
          %br/
          = t('sales.sale_customer.tel')
          = til sale.company_telephone
          %br/
          = t('sales.sale_customer.email')
          = til sale.company_email

app/views/sales/_table_headers.html.haml
- for_brand ||= false
%thead
  %tr
    %th= t('sales.table_headers.order_id')
    %th= t('sales.table_headers.date')
    %th= t('sales.table_headers.products')
    %th= t('sales.table_headers.value')
    %th= t('sales.table_headers.to_pay')
    %th= t('sales.table_headers.status')

app/views/sales/add_product.js.haml
= render partial: 'sales/update_form'

app/views/sales/add_product_error.js.haml
alert("Product was not found")

app/views/sales/delete_note.js.haml
$('#notes').empty();
$('#add-note-modal textarea').val('');
$('#add-note').show();

app/views/sales/empty.js.haml
= render partial: 'sales/update_form'

app/views/sales/event_tariffs.html.haml
%ul.breadcrumb
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('sales.event_tariffs.home')
  %li.divider
  %li= t('sales.event_tariffs.sales')
  %li.divider
  %li= t('sales.event_tariffs.event_tariffs')
.innerLR
  .row-fluid
    .span4
      %h3.heading-mosaic= t('sales.event_tariffs.event_tariffs')
= simple_nested_form_for current_store, url: update_extra_options_sales_path,
                                     html: { method: :post}, validate: true do |f|
  .innerLR
    = f.error_messages
    = hidden_field_tag :back_url, event_tariffs_sales_path
    = hidden_field_tag :message, t('sales.event_tariffs.message')
    .widget.widget-tabs
      .widget-head
        %ul
          %li.active
            = link_to '#productDescriptionTab', class: 'glyphicons calendar', :'data-toggle' => 'tab' do
              %i>
              = t('sales.event_tariffs.event_tariffs')
      .widget-body
        .tab-content
          #productDescriptionTab.tab-pane.active
            -#TODO NEED TO FIX store decorator
            = f.fields_for :event_tariffs, current_store.event_tariffs.blank? ? current_store.event_tariffs.build : current_store.event_tariffs
            = f.link_to_add :event_tariffs, class: 'btn btn-default btn-icon glyphicons circle_plus' do
              %i>
              = t('sales.event_tariffs.add_another_tariff')
    / // Widget END
    .heading-buttons
      .buttons.pull-right{:style => 'margin: 0;'}
        %button.btn.btn-primary.btn-icon.glyphicons.ok_2{ type: 'submit' }
          %i
          = t('sales.event_tariffs.save')
      .clearfix

app/views/sales/index.html.haml
#sales= render 'form'

app/views/sales/update.js.haml
- if resource.errors.blank?
  = render(:partial => 'sales/update_form')
- else
  alert("#{resource.errors.full_messages.join(", ")}")