config/routes.rb
    member do
      get :get_credit_note
      post :add_to_event
      get :check_certification_levels
      get :get_discount_level
      get :recalculate_event_price
      post :get_events
      post :load_sales
      post :load_ecp
    end

    get :update_certification_level_select, on: :collection
  end

  # FIXME: use polymorphic route
  resources :notes, only: [:update, :destroy]

  resources :categories
  resources :brands

  ################################# PRODUCTS ################################
  resources :products do
    collection do
      post :create_extra_option
      post :export
      post :barcode_export
    end
    member do
      post :print_barcode
      get :archived
      get :unarchived
    end
  end

  ################################# SALES ################################
  resources :sales do
    get :history, on: :collection
    get :event_tariffs, on: :collection
    post :pay_for_event, on: :collection
    post :update_extra_options, on: :collection

    collection do
      post :send_receipt_via_email
      get :close
      post :export_to_csv
    end

    member do
      post :add_events
      post :reopen_layby
      post :refund
      get :mark_as_complete
      post :add_product
      post :add_customer
      get  :products_list
      get  :customers_list
      delete :empty
      get :show_email_receipt_form
      get :add_customer_form
      get :add_product_form
      get :search_product
      post :add_note
      post :add_misc_product
    end
  end
  resources :purchase_orders do
    member do
      get :suppliers_list
      post :assign_supplier
      post :remove_supplier
      post :add_product
      get :products_list
      post :empty
      post :add_note
      get :download
      post :set_status
      get :update_order_form_after_send
      post :send_email_to_supplier
      put :set_expected_delivery
      put :update_amend
    end
  end
  resources :payments, only: [:update, :destroy]
  resources :sale_customers, only: [:destroy] do
    put :ignore_events, on: :member
  end

  resources :business_contacts, only: [] do
    resources :notes, only: [:create]
  end

  resources :suppliers do
    resources :notes, only: [:create]
    resources :business_contacts, except: [:index], :path => "/contacts"
    collection do
      get :sync_with_mailchimp
      post :export
    end
  end

  resources :settings, only: [:index, :edit, :update] do
    collection do
      [:user_profile, :stores, :sales, :events, :integrations, :billing, :select_agency, :edit_agency, :trips, :additionals, :edit_mailchimp_step_1,
       :edit_mailchimp_step_2, :print, :import_to_csv_step_1, :switch_store, :servicing, :boats, :emails, :email_example, :clear_data_page,
       :rentals, :restore_sale].each do |route|
        get route
      end
      [:update_stores, :update_store, :update_events, :update_integrations, :update_billing, :update_agency, :update_user].each do |route|
        put route
      end
      [:import_to_csv_step_2, :import, :clear_data].each do |route|
        post route
      end
    end
  end

  namespace :settings do
    resource :xero, only: [:update], controller: "xero" do
      collection do
        get :edit_xero
        get :connect_to_xero
        get :callback
        get :disconnect
        put :update_settings
        post :check_xero_tax_rates
        get :sync
      end
    end
    resource :scubatribe, only: [:create, :new] do
      collection do
        post :signup
      end
    end
  end

  resources :billings, only: [] do
    collection do
      post :stripe_callback
    end
  end

  resources :course_events, except: [:show], :path => "/events/courses" do
    collection do
      get :course_price
    end
    member do
      get :print_event_pickup,    to: 'events#print_event_pickup'
      get :print_event_manifest,  to: 'events#print_event_manifest'
    end
  end
  resources :other_events, except: [:show], :path => "/events/standard" do
    collection do
      get :trip_price
    end
    member do
      get :print_event_pickup,    to: 'events#print_event_pickup'
      get :print_event_manifest,  to: 'events#print_event_manifest'
      post :duplicate
    end
  end

  resources :events, only: [:index, :show, :update] do
    collection do
      get :get_events
      get :get_public_events
      get :list
      get :widget
      post :search
      post :print_resource_manifest
      post :print_staff_roster
      post :print_resource_utilisation
    end
    member do
      get :check_free_sets
      get :cancel_confirmation_no_registrations
      post :cancel
      get :cancel_confirmation_with_registrations
      get :cancel_complete
      get :print_event_pickup
      get :print_resource_manifest
      get :event_user_participants
    end
    resources :event_customer_participants do
      member do
        get :approve
        get :reject_form
        post :reject
        get :reject_paid_form
        post :reject_paid
      end
    end
  end
  resources :event_customer_participants, only: [] do
    delete :remove_from_sale, on: :member
    post :calculate_price, on: :collection
  end

  resources :staff_members do
    collection do
      get :sync_with_mailchimp
      post :export
      get :schedule
    end
    member do
      get :mark_as_day_off
      get :mark_as_available
    end
  end

  resources :users do
    resources :notes, only: [:create]
  end

  ############################################ REPORTS ##############################################
  resources :reports, only: [:index] do
    collection do
      get :sales_by_day
      get :sales_by_month
      get :sales_by_year
      get :sales_by_staff
      get :sales_by_brand
      get :sales_by_category
      get :sales_by_popular
      get :event_sales
      get :financial_reports
      get :edit_finance_report
      put :update_finance_report
    end
  end

  ############################################ BOOKING ##############################################
  resources :bookings, only: [] do
    collection do
      get :step_1
      post :step_2
      post :create_customer
      post :calculate_price
      get :cancel
      get :paypal_complete
    end
  end

  ################################# CUSTOMERS ################################
  resources :gift_card_types do
    member do
      get :pause
      get :resume
    end
  end

  resources :gift_cards, only: [:show, :update]

  resources :credit_notes, only: [:index]
  resources :services do
    collection do
      get :get_type_of_service
      get :add_item
    end
    member do
      post :complete
    end
    resources :service_notes, only: [:edit, :update, :destroy]
    resources :time_intervals, only: [:create] do
      collection do
        post :stop
      end
    end
  end

  resources :certification_levels, only: [:update]
  resources :event_trips, only: [:update]

  namespace :stores do
    resources :boats, only: [:update]
  end

  #RENTAL MODULE
  resources :rentals, except: [:new] do
    member do
      post :add_rental_product
      delete :remove_payment
      post :send_receipt_via_email
    end
  end

  ############################################ RENTAL PRODUCTS ##################################
  resources :rental_products do
    collection do
      get :search
      post :export
    end

    member do
      get :archived
      get :unarchived
    end
  end

  ############################################ SMART LISTS ##################################
  resources :smart_lists do
    member do
      post :send_email
      post :export
    end
    collection do
      get :get_values
    end
  end

  ############################################ REVIEWS / ScubaTribe #############################
  resources :reviews, only: [:index]
  resources :requests, only: [:index]

  ############################################ API ##############################################
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
      end
      resources :companies, only: [:create]
      resources :currencies, only: [:index]
      resources :customers, only: [:index, :show, :create, :update, :destroy]
      resources :events, only: [:index, :show, :create, :update, :destroy] do
        resources :event_user_participants, only: [:update, :create, :destroy]
        resources :event_customer_participants, only: [:update, :create, :destroy]
      end
      [:boats, :stores, :pages, :tax_rates].each do |res|
        resources res, only: [:index]
      end
      resources :categories, only: [:index, :show]
      resources :brands, only: [:index, :show]
      resources :event_trips, only: [:index, :show]
      resources :certification_agencies, only: [:index, :show]
      resources :users, only: [:index] do
        get :info, on: :collection
      end
      resources :sales, only: [:index, :show, :new] do
        collection do
          get :products
          post :remove_customer
        end
        member do
          post :add_customer
          post :add_product
          post :send_receipt
          post :add_misc_product
        end
      end
      resources :reports, only: [] do
        collection do
          [:sales_by_brand, :sales_by_category, :sales_by_day, :sales_by_products, :sales_by_staff_member,
           :financial_reports].each do |route|
            get route
          end
          match '/financial_reports/:id' => 'reports#financial_report_details', via: :get
          match '/financial_reports/:id' => 'reports#update_finance_report', via: :put
        end
      end
      resources :products, except: [:new, :edit]
    end
  end

  resources :pages, only: [] do
    collection do
      %w(change_current_store delete_image no_access search complete_setup).each do |route|
        get route.to_sym
      end
      %w[send_message send_support_request].each do |route|
        post route.to_sym
      end

app/helpers/reports_helper.rb
module ReportsHelper
  def show_months_head
    heads = []
    heads << content_tag(:th, nil, class: 'first')
    @duration.times do |index|
      heads << content_tag(:th, nil) do
        haml_tag :span, class: 'border'
        haml_tag :span, "#{ Date::MONTHNAMES[(@date + index.month).month] } #{ (@date + index.months).year }", style: Date::MONTHNAMES[(@date + index.month).month].eql?(Date::MONTHNAMES[Date.today.month]) ? 'color:yellow' : nil
      end
    end

    content_tag(:tr, heads.join.html_safe)
  end

  def show_table_row_with_currency title, collection, options = {}
    show_table_row "#{title} (#{current_store.currency.unit})".html_safe, collection, options = {}
  end

  def show_table_row title, collection, options = {}
    heads = []
    heads << content_tag(:td, title, class: 'important')
    collection.each do |price|
      heads << content_tag(:td, formatted_currency(price))
    end

    content_tag(:tr, heads.join.html_safe, options.merge!(:class => cycle(nil, "color")))
  end
end

app/views/reports/_financial_report.html.haml
- type = financial_report.invoice? ? t('reports.financial_reports.invoice') : t('reports.financial_reports.credit')
%tr
  %td.important
    = link_to "#{t('reports.financial_reports.sales_report', type: type)}: #{l(financial_report.created_at, format: :default)}", edit_finance_report_reports_path(:id => financial_report.id)
  %td= formatted_currency(financial_report.total_payments)
  %td= link_to t('reports.financial_reports.view_in_xero'), financial_report.xero_url, target: '_blank' if financial_report.sent?

app/views/reports/_sales_by_day.html.haml
.widget
  .widget-head
    %h4.heading= t('reports.sales_by_day.sales_by_day')
  .widget-body
    = form_tag url_for(action: params[:action], controller: params[:controller]), method: :get do |f|
      .row-fluid
        .span3
          #datetimepicker1.input-append.date
            %input.span11{name: 'date', type: 'text', value: '', class: 'span12 datepicker'}/
            %span.add-on
              %i.icon-calendar
        .span3
          %button.btn.btn-small.btn-primary.btn-icon.glyphicons.history{ type: 'submit' }
            %i>
            = t('reports.sales_by_day.refine_dates')
    %table.table.table-bordered.table-condensed.table-striped.table-primary.table-vertical-center
      %thead
        %tr
          %th
          - (@day - @number_of_days.days..@day + @number_of_days.days).each do |current_date|
            %th{style: current_date.today? ? 'color: yellow;' : ''}
              = current_date.strftime('%d %b')
      %tbody
        = show_table_row_with_currency t('reports.sales_by_day.sales_tax'), @report_by_day[:sales_inc_tax]
        = show_table_row_with_currency t('reports.sales_by_day.tax'), @report_by_day[:taxes], class: 'color'
        = show_table_row_with_currency t('reports.sales_by_day.taxable_revenue'), @report_by_day[:taxable_revenue], class: 'color'
        = show_table_row_with_currency t('reports.sales_by_day.cost_of_goods'), @report_by_day[:cost_of_goods]
        = show_table_row_with_currency t('reports.sales_by_day.gross_profit'), @report_by_day[:gross_profit], class: 'color'
        = show_table_row_with_currency t('reports.sales_by_day.refunds'), @report_by_day[:refunds]
        = show_table_row_with_currency t('reports.sales_by_day.tax_refunds'), @report_by_day[:tax_refunds]

app/views/reports/_sales_by_month.html.haml
.widget
  .widget-head
    %h4.heading= title
  .widget-body
    = render 'period_select_form'
    %table.table.table-bordered.table-condensed.table-striped.table-primary.table-vertical-center
      %thead
        = show_months_head
      %tbody
        = show_table_row_with_currency t('reports.sales_by_day.sales_tax'), @report_by_month[:sales_inc_tax]
        = show_table_row_with_currency t('reports.sales_by_day.tax'), @report_by_month[:taxes], :class => "color"
        = show_table_row_with_currency t('reports.sales_by_day.taxable_revenue'), @report_by_month[:taxable_revenue], :class => "color"
        = show_table_row_with_currency t('reports.sales_by_day.cost_of_goods'), @report_by_month[:cost_of_goods]
        = show_table_row_with_currency t('reports.sales_by_day.gross_profit'), @report_by_month[:gross_profit], :class => "color"
        = show_table_row_with_currency t('reports.sales_by_day.refunds'), @report_by_month[:refunds]
        = show_table_row_with_currency t('reports.sales_by_day.tax_refunds'), @report_by_month[:tax_refunds]

app/views/reports/_sales_by_year.html.haml
.widget
  .widget-head
    %h4.heading= title
  .widget-body
    %table.table.table-bordered.table-condensed.table-striped.table-primary.table-vertical-center
      %thead
        %tr
          %th
          - (Date.today.year - @period..Date.today.year).each do |year|
            %th{style: year.eql?(Date.today.year) ? 'color: yellow;' : ''}
              = year
      %tbody
        = show_table_row_with_currency t('reports.sales_by_day.sales_tax'), @report_by_year[:sales_inc_tax]
        = show_table_row_with_currency t('reports.sales_by_day.tax'), @report_by_year[:taxes], :class => "color"
        = show_table_row_with_currency t('reports.sales_by_day.taxable_revenue'), @report_by_year[:taxable_revenue], :class => "color"
        = show_table_row_with_currency t('reports.sales_by_day.cost_of_goods'), @report_by_year[:cost_of_goods]
        = show_table_row_with_currency t('reports.sales_by_day.gross_profit'), @report_by_year[:gross_profit], :class => "color"
        = show_table_row_with_currency t('reports.sales_by_day.refunds'), @report_by_year[:refunds]
        = show_table_row_with_currency t('reports.sales_by_day.tax_refunds'), @report_by_year[:tax_refunds]

app/views/reports/_table_body.html.haml
= render 'period_select_form'
%table.table.table-bordered.table-condensed.table-striped.table-primary.table-vertical-center
  %thead
    = show_months_head
  %tbody
    - report.each do |k, v|
      = show_table_row k, v, class: cycle('', 'color')

app/views/reports/edit_finance_report.html.haml
:ruby
  @sale_ids = current_store.sales.for_invoice(@finance_report.working_time).map(&:id)
  @rentals  = current_store.rentals.for_invoice(@finance_report.working_time)

%ul.breadcrumb.hidden-print
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('.home')
  %li.divider
  %li= t('.reports')
.innerLR
  .row-fluid
    .span9
      %h3.heading-mosaic
        = t('.financial_reports')
    .span3.right
      .buttons.hidden-print
        = link_to "javascript:window.print()", class: 'btn btn-small btn-default btn-icon glyphicons print' do
          %i
          = t('.print')
  .row-fluid
    .span6
      .widget
        .widget-head
          %h4.heading= t('.register_details')
        .widget-body.list
          %ul
            %li
              %span= t('.shop')
              %span.count #{current_store.name}
            %li
              %span= t('.business')
              %span.count #{current_company.name}
    .span6
      .widget
        .widget-head
          %h4.heading= t('.open_close_times')
        .widget-body.list
          %ul
            %li
              %span= t('.opened')
              %span.count #{l(@finance_report.working_time.open_at, formats: :default)}
            %li
              %span= t('.closed')
              %span.count #{l(@finance_report.working_time.close_at, formats: :default)}
  .row-fluid
    .widget
      .widget-head
        %h4.heading= t('.sales')
      .widget-body.list
        %ul
          %li
            %span
              %strong= t('.completed_sales')
            %span.count #{formatted_currency @finance_report.complete_payments}
          %li
            %span= t('.tax_total')
            %span.count #{formatted_currency @finance_report.tax_total}
          %li
            %span
              %strong= t('.discounts')
            %span.count #{formatted_currency @finance_report.discounts}
          %li
            %span
              %strong= t('.total_payments')
            %span.count #{formatted_currency @finance_report.total_payments}

  .row-fluid
    .widget
      .widget-head
        %h4.heading= t('.category_payments')
      .widget-body
        %table.table.table-bordered.table-condensed.table-striped.table-primary.table-vertical-center
          %thead
            %tr
              %th= t('.category_payments')
              %th= t('.sales')
          %tbody
            - current_store.categories.each do |category|

              -#TODO: MiscellaneousProduct does not have sale_productable_id, therefore causing SaleProduct section below to break. We need to check product and if sale_productable_id blank, use productable_category_name from MiscellaneousProduct instead. 

              - price = SaleProduct.where(sale_id: @sale_ids, sale_productable_id: category.all_product_ids).sum(&:smart_line_item_price) + Rented.where(rental_id: @rentals, rental_product_id: category.rental_products).sum(&:line_item_price)
              - unless price.zero?
                %tr
                  %td.important #{category.name}
                  %td= formatted_currency price
            - SaleProduct.where(sale_id: @sale_ids, sale_productable_type: ['EventCustomerParticipant', 'MaterialPrice']).each do |sp|
              - ecp = sp.sale_productable
              - if ecp.class != MaterialPrice
                %tr
                  %td.important= ecp.event.name
                  %td= ecp.event.decorate.price
                - ecp.event_customer_participant_options.each do |ecpo|
                  - unless ecpo.quantity.zero? || ecpo.unit_price.zero?
                    %tr
                      %td.important= ecpo.name
                      %td= formatted_currency(ecpo.line_item_price)
              - if ecp.class == MaterialPrice && !ecp.price.zero?
                %tr
                  %td.important= ecp.name
                  %td= formatted_currency ecp.price

            - SaleProduct.only_services.where(sale_id: @sale_ids).each do |s|
              - unless s.sale_productable.complimentary_service
                - s.sale_productable.kits.each do |kit|
                  %tr
                    %td.important= kit.type_of_service.name_for_sale
                    %td= kit.type_of_service.decorate.price
                  - if kit.type_of_service.service_kit
                    - price = kit.type_of_service.service_kit.line_item_price
                    - unless price.zero?
                      %tr
                        %td= kit.type_of_service.service_kit.name_for_sale
                        %td= formatted_currency(price)
                - s.sale_productable.products.each do |p|
                  %tr
                    %td= p.name
                    %td= p.decorate.price

  = form_for current_store, url: update_finance_report_reports_path, html: { method: :put } do |f|
    = hidden_field_tag :id, @finance_report.id
    = f.error_messages
    .row-fluid
      .widget
        .widget-head
          %h4.heading= t('.payments')
        .widget-body
          %table.table.table-bordered.table-condensed.table-striped.table-primary.table-vertical-center
            %thead
              %tr
                %th= t('.payment_type')
                %th= t('.amount')
                %th= t('.to_post')
            %tbody
              = f.fields_for :finance_reports, f.object.finance_reports.where(id: @finance_report.id) do |ff|
                = ff.fields_for :finance_report_payments, @finance_report.finance_report_payments.complete do |build|
                  %tr
                    %td.important #{build.object.name}
                    %td #{formatted_currency build.object.amount}
                    %td
                      - if @finance_report.sent?
                        #{formatted_currency build.object.custom_amount}
                      - else
                        .input-prepend.margin-bottom-none
                          %span.add-on #{current_store.currency.unit.html_safe}
                          = build.text_field :custom_amount, class: 'span12', value: number_with_precision(build.object.custom_amount, precision: current_store.currency.precision)
    .row-fluid
      .widget
        .widget-head
          %h4.heading Float
        .widget-body
          %table.table.table-bordered.table-condensed.table-striped.table-primary.table-vertical-center
            %thead
              %tr
                %th= t('.t_time')
                %th= t('.t_staff')
                %th= t('.t_action')
                %th= t('.t_amount')
                %th= t('.t_notes')
            %tbody
              = f.fields_for :tills, @tills do |ff|
                %tr
                  %td.important  #{l(ff.object.created_at, formats: :default)}
                  %td= ff.object.user.full_name
                  %td
                    %label.checkbox.inline{style: 'padding-left: 10px; padding-top:0px;'}
                      = ff.radio_button :take_out, "1", checked: ff.object.take_out?
                      = t('.t_take_out')

                    %label.checkbox.inline{style: 'padding-top:0px;'}
                      = ff.radio_button :take_out, "0", checked: !ff.object.take_out?
                      = t('.t_put_in')
                  %td
                    .input-prepend.margin-bottom-none
                      %span.add-on #{current_store.currency.unit.html_safe}
                      = ff.text_field :amount, class: 'span12', value: number_with_precision(ff.object.amount, precision: current_store.currency.precision)
                  %td
                    = ff.text_field :notes, class: 'span12 margin-bottom-none', value: ff.object.notes

    %button.btn.btn-primary.btn-icon.glyphicons.ok_2.pull-right.hidden-print{ type: 'submit' }
      %i
      = t('.save_totals')

app/views/reports/event_sales.html.haml
%ul.breadcrumb.hidden-print
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('reports.event_sales.home')
  %li.divider
  %li= t('reports.event_sales.reports')
.innerLR
  .row-fluid
    .span9
      %h3.heading-mosaic= t('reports.event_sales.report_event_sales')
    .span3.right
      .buttons.hidden-print
        = link_to "javascript:window.print()", class: 'btn btn-small btn-default btn-icon glyphicons print' do
          %i
          = t('reports.edit_finance_report.print')
  .widget
    .widget-head
      %h4.heading= t('reports.event_sales.event_sales')
    .widget-body
      = render 'period_select_form'
      %table.table.table-bordered.table-condensed.table-striped.table-primary.table-vertical-center
        %thead
          = show_months_head
        %tbody
          = show_table_row_with_currency t('reports.event_sales.dive_courses'), @report[:dive_courses], class: 'color'
          = show_table_row_with_currency t('reports.event_sales.dive_trips'), @report[:dive_trips], class: 'color'
          = show_table_row_with_currency t('reports.event_sales.totals'), @report[:total], class: 'color'

app/views/reports/financial_reports.html.haml
%ul.breadcrumb.hidden-print
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('reports.financial_reports.home')
  %li.divider
  %li= t('reports.financial_reports.reports')
.innerLR
  .row-fluid
    .span12
      %h3.heading-mosaic= t('reports.financial_reports.finance_reports')
.innerLR
  .widget
    .widget-head
      %h4.heading= t('reports.financial_reports.finance_reports')
    .widget-body
      = form_tag url_for(action: params[:action], controller: params[:controller]), method: :get, class: 'refinements' do
        .row-fluid
          .span2
            = select_tag :month, options_for_select(Date::MONTHNAMES.compact, selected: Date::MONTHNAMES[@period.month]), class: 'selectpicker span12'
          .span2
            = select_tag :year, options_for_select((Date.today.year - 6..Date.today.year).to_a.reverse, selected: @period.year), class: 'selectpicker span12'
          .span2
            %button.btn.btn-small.btn-primary.btn-icon.glyphicons.history{ type: 'submit' }
              %i>
              = t('reports.financial_reports.refine_dates')
      %table.table.table-bordered.table-condensed.table-striped.table-primary.table-vertical-center
        %thead
          %tr
            %th
            %th= t('reports.financial_reports.t_total_sales')
            %th= t('reports.financial_reports.t_xero')
        %tbody
          = render partial: "financial_report", collection: @finance_reports

app/views/reports/sales_by_brand.html.haml
%ul.breadcrumb.hidden-print
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('reports.sales_by_brand.home')
  %li.divider
  %li= t('reports.sales_by_brand.reports')
.innerLR
  .row-fluid
    .span9
      %h3.heading-mosaic= t('reports.sales_by_brand.report_sales_by_brand')
    .span3.right
      .buttons.hidden-print
        = link_to "javascript:window.print();", class: 'btn btn-small btn-default btn-icon glyphicons print' do
          %i
          = t('reports.edit_finance_report.print')
  .widget
    .widget-head
      %h4.heading= t('reports.sales_by_brand.sales_by_brand')
    .widget-body
      = render 'table_body', report: @report

app/views/reports/sales_by_category.html.haml
%ul.breadcrumb.hidden-print
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('reports.sales_by_category.home')
  %li.divider
  %li= t('reports.sales_by_category.reports')
.innerLR
  .row-fluid
    .span9
      %h3.heading-mosaic= t('reports.sales_by_category.report_sales_by_category')
    .span3.right
      .buttons.hidden-print
        = link_to "javascript:window.print();", class: 'btn btn-small btn-default btn-icon glyphicons print' do
          %i
          = t('reports.edit_finance_report.print')
  .widget
    .widget-head
      %h4.heading= t('reports.sales_by_category.sales_by_category')
    .widget-body
      = render 'table_body', report: @report

app/views/reports/sales_by_day.html.haml
%ul.breadcrumb.hidden-print
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('reports.sales_by_time.home')
  %li.divider
  %li= t('reports.sales_by_time.reports')
.innerLR
  .row-fluid
    .span9
      %h3.heading-mosaic= t('reports.sales_by_time.report_sales_by_time')
    .span3.right
      .buttons.hidden-print
        = link_to "javascript:window.print();", class: 'btn btn-small btn-default btn-icon glyphicons print' do
          %i
          = t('reports.edit_finance_report.print')
  = render 'sales_by_day'

app/views/reports/sales_by_month.html.haml
%ul.breadcrumb.hidden-print
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('reports.sales_by_time.home')
  %li.divider
  %li= t('reports.sales_by_time.reports')
.innerLR
  .row-fluid
    .span9
      %h3.heading-mosaic= t('reports.sales_by_time.sales_by_month')
    .span3.right
      .buttons.hidden-print
        = link_to "javascript:window.print();", class: 'btn btn-small btn-default btn-icon glyphicons print' do
          %i
          = t('reports.edit_finance_report.print')
  = render 'sales_by_month', title: t('reports.sales_by_time.sales_by_month')

app/views/reports/sales_by_popular.html.haml
%ul.breadcrumb.hidden-print
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('reports.sales_by_popular.home')
  %li.divider
  %li= t('reports.sales_by_popular.reports')
.innerLR
  .row-fluid
    .span9
      %h3.heading-mosaic= t('reports.sales_by_popular.report_sales_by_popular_products')
    .span3.right
      .buttons.hidden-print
        = link_to "javascript:window.print();", class: 'btn btn-small btn-default btn-icon glyphicons print' do
          %i
          = t('reports.edit_finance_report.print')
  .widget
    .widget-head
      %h4.heading= t('reports.sales_by_popular.sales_by_popular_products')
    .widget-body
      = render 'table_body', report: @report.sort_by {|k,v| v.sum}.reverse
      = paginate @products

app/views/reports/sales_by_year.html.haml
%ul.breadcrumb.hidden-print
  %li
    = link_to root_path, class: 'glyphicons home' do
      %i
      = t('reports.sales_by_time.home')
  %li.divider
  %li= t('reports.sales_by_time.reports')
.innerLR
  .row-fluid
    .span9
      %h3.heading-mosaic= t('reports.sales_by_time.report_sales_by_time')
    .span3.right
      .buttons.hidden-print
        = link_to "javascript:window.print();", class: 'btn btn-small btn-default btn-icon glyphicons print' do
          %i
          = t('reports.edit_finance_report.print')
  = render 'sales_by_year', title: t('reports.sales_by_time.sales_by_year')